services:
  - type: web
    name: rsna-knee-classifier
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3008
    healthCheckPath: /api/health
    autoDeploy: true
